version: "3.9"

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zyxwv
      - POSTGRES_DB=userdb
    ports:
    - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 1

  user-service:
    image: user-apis
    restart: always
    build: .
    ports:
    - "8081:8081"
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
    links:
    - db
