// Code generated by sqlc. DO NOT EDIT.

package server

import (
	"database/sql"
)

type User struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Email   string         `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Age     sql.NullInt32  `json:"age"`
	Address sql.NullString `json:"address"`
}
